# Generated by Django 2.2.4 on 2019-09-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190902_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
