# Generated by Django 2.2.4 on 2019-10-24 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191017_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 16, 32, 54, 62817)),
        ),
    ]
