# Generated by Django 2.2.4 on 2019-10-24 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191024_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 24, 16, 36, 2, 416952)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='codes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
