# Generated by Django 2.2.4 on 2019-10-28 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191024_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 28, 12, 21, 40, 186567)),
        ),
    ]
