# Generated by Django 2.2.4 on 2019-10-28 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191028_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 28, 13, 9, 56, 278586)),
        ),
    ]
