# Generated by Django 2.2.4 on 2019-09-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='pics')),
            ],
        ),
    ]
