# Generated by Django 2.2.4 on 2019-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='msgcount',
            field=models.IntegerField(default=1),
        ),
    ]
