# Generated by Django 2.2.4 on 2019-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190927_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='qname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='quotes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
