# Generated by Django 2.2.4 on 2019-09-27 08:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190927_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(default='gchgkch'),
            preserve_default=False,
        ),
    ]
