# Generated by Django 2.2.4 on 2019-10-10 06:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
