# Generated by Django 2.2.4 on 2019-10-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191010_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
