# Generated by Django 2.2.4 on 2019-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191010_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
