# Generated by Django 2.2.4 on 2019-10-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
